### ISSUE TITLE
How to use in a script with import?

### ISSUE THREAD

**Issue by Trixpua** [povilasb/pyigd#1]
How can I use it in a script using import igd?

I want to add a port, I think is something like this igd.Gateway.add_port_mapping(), but how I need to set the arguments?

**Comment by povilasb** [comment]
Good question. Although, this is one of the goals I haven't tested such scenario and optimized for it.

Yes you're right about using `Gateway` and you need to use [PortMapping](https://github.com/povilasb/pyigd/blob/master/igd/proto.py#L4) object to set the arguments.

Also, I've restructured code a bit and wrote an example: https://github.com/povilasb/pyigd/blob/master/examples/add_port_mapping.py - hope that helps :)

When running an example install `igd` from github: `$ pip3 install git+https://github.com/povilasb/pyigd`
See if that helps and I'll tag a new version and upload to pypi, if everything's ok :)

**Comment by Trixpua** [comment]
Thank you @povilasb ! I will run some tests this week and send a feedback to you!

**Comment by povilasb** [comment]
Well, did that work?:)
